Testing schemathesis with CD pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,13 +54,21 @@ jobs:
             --ruleset /work/.spectral.yaml \
             /work/openapi.yaml || { echo "❌ Spectral lint failed"; exit 1; }
 
-      # 7️⃣ Start SSH agent
+      #8️Run Schemathesis API tests
+      - name: Run Schemathesis
+        run: |
+          echo "Running Schemathesis API tests..."
+          PYTHONPATH=$(pwd) schemathesis run http://localhost:8000/openapi.json \
+            --checks not_a_server_error,status_code_conformance,content_type_conformance,response_schema_conformance,negative_data_rejection \
+            || { echo "❌ Schemathesis tests failed"; exit 1; }
+
+      # 8️⃣ Start SSH agent
       - name: Start SSH agent
         uses: webfactory/ssh-agent@v0.9.0
         with:
           ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
 
-      # 8️⃣ Determine which script to run
+      # 9️⃣ Determine which script to run
       - name: Set deployment variables
         id: vars
         run: |
@@ -76,7 +84,7 @@ jobs:
             exit 0
           fi
 
-      # 9️⃣ Deploy via SSH
+      # 10️⃣Deploy via SSH
       - name: Run deploy script on droplet
         env:
           DROPLET_USER: ${{ secrets.DROPLET_USER }}
